### ISSUE TITLE
Missing Dockerfile?

### ISSUE THREAD

**Issue by akessner** [Netflix/vizceral-example#10]
When trying to build the project from Docker I got the following error:

akessner@ubuntuFirst:~$ docker build -t akessner/vizceral-example .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/akessner/Dockerfile: no such file or directory

Docker's hello world works fine.
Creating the file complains that it is empty.

 What should be in the Dockerfile?

**Comment by akessner** [comment]
It also seems to be missing the package.json file?

Sending build context to Docker daemon 182.5 MB
Step 1 : FROM mhart/alpine-node
 ---> a437893a1943
Step 2 : RUN mkdir -p /usr/src/app
 ---> Using cache
 ---> 82d5926b1dd8
Step 3 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 0474804cf84a
Step 4 : COPY package.json /usr/src/app/
lstat package.json: no such file or directory

**Comment by jrsquared** [comment]
You are trying to run docker build from your home directory and not from the vizceral-example directory.

**Comment by jrsquared** [comment]
Assuming that the above addressed the issue, closing.
