### ISSUE TITLE
Babel/JSX

### ISSUE THREAD

**Issue by jbrekelmans** [Netflix/vizceral-example#11]
For me the the babel/react loader seems to be not working. I followed the README and did "npm install" followed by "npm run dev" using npm version 3.10.6 (and node version 4.2.6, if that's relevant). I got an error saying that <TrafficFlow /> was invalid syntax in "app.jsx". Any tips? Is there something missing in dependencies in package.json?

**Comment by jrsquared** [comment]
Someone had a similar issue with the vizceral project itself when trying to run webpack from the node_modules directory.  Is that what you are trying to do? I made the same change to this project (7ffad14bbcd9b1f0d1ecce01c9da0b4462b83cf6) and published a new version to npm.

**Comment by jbrekelmans** [comment]
I found out what the problem was: I was missing the .babelrc file because I downloaded a zip, moved it's contents through select all -> cut -> paste (but I didn't move the hidden files).
