### ISSUE TITLE
updateData

### ISSUE THREAD

**Issue by mrmarss** [Netflix/vizceral-example#12]
Hi, so I have introduced an interval each second in the trafficFlow.jsx. I connected this interval with the beginSampleData function, which I also did some slight modification to no longer clear this.traffic. As a result the sample_data.json is read into a json object, which is then passed to updateData(). I noticed that the "last updated" parameter gets updated with each time I write a new value to the json file, but when "metrics" are altered, the animation does not change/update in realtime to reflect the traffic change. I feel I am missing something, and would greatly appreciate some more direction.

**Comment by jrsquared** [comment]
Ah, currently https://github.com/Netflix/vizceral-react/blob/master/src/vizceral.jsx#L104 requires any root level node to have a different `updated` property than before.  This check should be moved out of the react wrapper, but for now, if you just add an this field to any of the root level .nodes, and update it every time, it should get you moving.

**Comment by mrmarss** [comment]
Perfect, that was the problem. I wasn't changing the updated property. Thank you for the help.
