### ISSUE TITLE
Previous graph content remains if active filters end up filtering all nodes or connections or both

### ISSUE THREAD

**Issue by aSqrd-eSqrd** [Netflix/vizceral-example#17]
I've still been monkeying with my own filters for my data and came across a disconcerting edge case.  If the filter(s) that are "active" just so happen to filter every node or connection or both away the graph never "updates" or blanks as I was expecting.

What causes it to be particularly disconcerting is that the particles stop and so it appears that the display has frozen.  I've attached a JSON file that if you set the RPS filter in vizceral-example to "high" it will filter all of the connections away.  If you move it one step lower (to the right from "high") then one of the two connections will be filtered and you will see the graph update (so long as you set the RPS filter to "high", then moved it to a lower setting).

I searched and searched for something that was causing the graph to not re-layout, but couldn't find anything that seemed to behave any different between everything-filtered, partially-filtered, and nothing-filtered.

If you use the attach file as the "sample_data.json" with the stock vizceral-example to reproduce the issue.

Thanks for your great work.
[everything_filtered_out_data.txt](https://github.com/Netflix/vizceral-example/files/579536/everything_filtered_out_data.txt)

**Comment by jrsquared** [comment]
Pushed fix to master, will be in the next release.
