### ISSUE TITLE
Rerender region

### ISSUE THREAD

**Issue by Baransu** [Netflix/vizceral-example#22]
I'm trying to dynamically update data. While providing 2 different `JSON` files with data (first `sample_data.json`, then `sample_data_simple.json` after 5 seconds), I expect region view to remove regions which are not present within `updatedTraffic`. How can I force Vizceral to update regions correctly?

**Comment by jrsquared** [comment]
Addressed in https://github.com/Netflix/vizceral/commit/dea6b2e44447c845af545bf30064de90ec364362 and pushed in vizceral@4.3.2. If you make sure dependencies are fully up to date, `vizceral-react` should pull in `vizceral@4.3.2`.
