### ISSUE TITLE
Can't install example

### ISSUE THREAD

**Issue by bcronrath** [Netflix/vizceral-example#26]
getting: 

Module parse failed: /Users/brian.cronrath/node_modules/vizceral-example/src/app.jsx Unexpected token (14:4)
You may need an appropriate loader to handle this file type.

Anyone know how I can resolve?

**Comment by jrsquared** [comment]
Please do not try to `npm install` vizceral-example, especially from your home directory, that's going to be a bad time.

I just tried following the steps in the readme and ran into no issues. Please follow those steps and let me know if you have any issues that way.
