### ISSUE TITLE
Integrating visceral

### ISSUE THREAD

**Issue by mmeliani** [Netflix/vizceral-example#28]
@jrsquared I need your help to integrate Visceral to my project, 
i read the post "Getting started" and i still have an issue about the JSON to be feed into updatedata(), 
indeed i make a http request to get a json object then i transform this json object into JSON which is understood by update data but when i inject it, it's doesn't work... here my html file : 

[html.txt](https://github.com/Netflix/vizceral-example/files/896372/html.txt)

I get the new json object from the scope of my controller and i injected to updatedata(scope), and it didn't work and no error went out and Vizceral canvas always height = 0
thanks in advance for your response,

**Comment by jrsquared** [comment]
Can you show me what `scope` equals after line 12?

**Comment by mmeliani** [comment]
it depends to the event in the body when i make onclick the value its an object (fine) but when i make onload the value is undefined, it's too weird and cannot for the life of me figure out what is wrong.

**Comment by jrsquared** [comment]
I can only help debug vizceral not loading if I know the value that is being passed into `viz.updateDate(scope)`

When `scope` is an object, does vizceral load fine? If it does not, what is `scope` when it is an object?

**Comment by jrsquared** [comment]
Again, what is the value of `scope` being passed into `viz.updateData(scope)`? I cannot help unless I know that.

**Comment by mmeliani** [comment]
{"name":"LDAP","renderer":"global","layout":"ltrTree","nodes":[{"name":"ldap_1"},{"name":"client_1"},{"name":"ldap_db1"},{"name":"ldap_2"},{"name":"client_2"},{"name":"ldap_db1"}],"connections":[{"source":"client_1","target":"ldap_1","metrics":{"normal":12,"danger":0},"metadata":{"streaming":true}},{"source":"ldap_1","target":"ldap_db1","metrics":{"normal":25,"danger":0},"metadata":{"streaming":true}},{"source":"client_2","target":"ldap_2","metrics":{"normal":102,"danger":1},"metadata":{"streaming":true}},{"source":"ldap_2","target":"ldap_db1","metrics":{"normal":25,"danger":0},"metadata":{"streaming":true}}]}

**Comment by mmeliani** [comment]
` var demo=angular.module('demo' , []);
		 demo.controller('metricsCtrl', function($scope, $http)
			{	
				$http.get('http://localhost:8080/api/v1/metrics', {
                headers: { 'Authorization': 'Basic a2VybmVsc3B==' }
            }).success(function (response)
				{
			 		// transform to JSON format supported by Vizceral 
					var response = response; 
		                        var nodes = []; 
			 		var connections = []; 
			 		
			 		for (var index=0; index < response.length ; index++)
			 		{
			 			
			 				// building nodes and check if nodes in parameter is already existed
			 				var name = response[index].id ; 
			 				var source= response[index].in[0].id ;
			 				var target= response[index].out[0].id ;
			 				nodes.push({name : name ,}) ;
			 				nodes.push({name : source ,}) ;
			 				nodes.push({name : target ,});
			 				
			 				
			 				// building connections 
			 				
			 				// first part with in 
			 				
			 				var normalIn = response[index].in[0].ok ; 
			 				var dangerIn = response[index].in[0].err ; 
			 				var sourceIn = response[index].in[0].id ; 
			 				var targetIn = response[index].id ; 
			 				
			 				connections.push
			 				(
			 					{
			 						source : sourceIn ,
			 						target : targetIn , 
			 						metrics : 
			 						{
			 							normal : normalIn , 
			 							danger : dangerIn  
			 							
			 						}, 
			 						metadata : 
			 						{
			 							streaming: true 
			 						}	
			 					
			 					}		
			 				); 
			 				
			 				// second part with Out 
			 				
			 				var normalOut = response[index].out[0].ok ; 
			 				var dangerOut = response[index].out[0].err ; 
			 				var sourceOut = response[index].id ; 
			 				var targetOut = response[index].out[0].id ; 
			 				
			 				connections.push
			 				(
			 					{
			 						source : sourceOut ,
			 						target : targetOut , 
			 						metrics : 
			 						{
			 							normal : normalOut , 
			 							danger : dangerOut  
			 							
			 						}, 
			 						metadata : 
			 						{
			 							streaming: true 
			 						}	
			 					
			 					}		
			 				);
			 					
			 				
			 		}
			 		// end loop for 
			 		
			 		// get response in JSON expected by Vizceral 
			 		
			 	var data = JSON.parse(JSON.stringify({name: 'LDAP' ,  renderer: 'global', layout: 'ltrTree' , nodes : nodes , connections: connections}));
			 	 // var data = JSON.stringify({name: 'LDAP' ,  renderer: 'global', layout: 'ltrTree' , nodes : nodes , connections: connections});
			 	$scope.metrics = data ;
			 	})
					.error(function (err) {
					alert('Error!');
					});
				
			 	// end http.get 
			  
			 
		 });`

**Comment by jrsquared** [comment]
The data is fine and if I replace `sample_data.json` in this project with that data, it loads. So it is most likely a problem with how you are loading/using vizceral with angular.

I'll bet that $http hasn't finished getting the data by the time body onload() fires.
Try just pasting that JSON you have above directly into what you put here as html.txt and see if it loads.  If that works, then you are just trying to updateData before you have the data on the scope of the angular component.  Try to have the onload() initiate the $http call, and have a callback or a listener to actually `updateData` on the vizceral object.

**Comment by mmeliani** [comment]
it works when i past the JSON, i initiate the http call in onload() but i didn't know how to set a callback or a listener to updateData on the vizceral object. any hints how to set it please ?

**Comment by jrsquared** [comment]
I don't know why you're doing the http call in an angular controller like that and having the vizceral object not in the angular world. If you have the vizceral object exist in the angular controller, it would be easy. If you want to have the vizceral canvas still exist outside the angular world, I would probably just use a simple [DOM Event](https://developer.mozilla.org/en-US/docs/Web/Events).  Since this is more a question about how to use angular, I'm going to close this issue.  This would be better answered in an angular forum.

**Comment by mmeliani** [comment]
thanks for your help it works, as i get the json file with a HTTP request. how vizceral update data if the json i get change ? any hints please ?

**Comment by jrsquared** [comment]
Just call updateData again with the new JSON

**Comment by mmeliani** [comment]
I tried it but it didn't work here my setinterval funtion to call update data every seconds : 

setInterval ( function(){
var json = the new json;
updatedata(json); 
} , 20000)

eventually i did not know how to call update data. thanks in advance
