### ISSUE TITLE
region Loading 

### ISSUE THREAD

**Issue by rothen25** [Netflix/vizceral-example#29]
Hi Guys , I have a issue about the display of the nodes. Certain nodes display correctly but some nodes have as a description " region loading " .Thanks for your explanation and help .
![regionloading](https://cloud.githubusercontent.com/assets/10595084/24864495/b8a42aea-1e04-11e7-8213-915ec12d68c1.PNG)

**Comment by jrsquared** [comment]
The current logic for the loading message is on https://github.com/Netflix/vizceral/blob/master/src/global/globalNode.js#L37

If the node is an entry node or has children nodes, then it is thought of as being loaded. When the global graph was first created, it had a requirement of region graphs under each node.

We currently still have the requirement that it shows `REGION LOADING` when the regional graph hasn't loaded yet, but if you can think of away to preserve this functionality for us while still satisfying your use case, I welcome a PR!
