### ISSUE TITLE
Blank screen with no nodes

### ISSUE THREAD

**Issue by AnandJayaraman** [Netflix/vizceral-example#3]
Hi,

I followed the instructions as specified in the  Github site. The server was started using 

npm run dev

On going to the localhost link, i see a black screen which has the top pane with VIZCERAL, Feedback, Global, Filters, Display.

There are no nodes displayed. 

Is there anything to be done to display the nodes from sample json?

Regards
Anand

**Comment by rdgreis** [comment]
Same here...

**Comment by jrsquared** [comment]
@AnandJayaraman @rdgreis 
What browser and version are you running?
Are there any errors in the console?

**Comment by rdgreis** [comment]
@jrsquared 
Google Chrome: Version 51.0.2704.103 m (64-bit)
![vizceral](https://cloud.githubusercontent.com/assets/1106724/17778697/39284b28-6565-11e6-849e-5f79a2f868f8.PNG)

@AnandJayaraman it works on firefox. :)

**Comment by jrsquared** [comment]
@rdgreis @AnandJayaraman 

Ah, yeah, that's not vizceral specific. The `Error creating WebGL context.` means that Chrome is having trouble with WebGL in general.  Vizceral requires WebGL. If you believe your system can handle/support WebGL, then you can check https://github.com/mrdoob/three.js/issues/4927 for a few different approaches that have been successful for different people.

If you cannot load https://get.webgl.org/, three.js will not work, and transitively Vizceral will not work. This is then a bug that you should report to Chrome.

A few approaches that have worked:

* Make sure `Use hardware acceleration when available.` is checked in your Chrome settings.
* If it is already checked, try unchecking it, restarting chrome, checking it, and restarting again.
* Like @rdgreis said, use Firefox ;) Most Vizceral development is done using Chrome, so it's not a general problem with Chrome and Vizceral, but if you are seeing WebGL problems with Chrome, Firefox may not have the same issues.

**Comment by jrsquared** [comment]
Closing this assuming my previous comment addressed the issue.

**Comment by AnandJayaraman** [comment]
Yes, your comment helped but the underlying issue was it wasn't working
because i was using browser in VDI
