### ISSUE TITLE
vizceral npm build errors

### ISSUE THREAD

**Issue by prabhurangan** [Netflix/vizceral-example#38]
npm run build:js

> vizceral@4.3.8 build:js /opensource/vizceral-example/node_modules/vizceral
> webpack --bail && webpack --bail -p

Hash: 4b7e17546eabf6279017
Version: webpack 1.15.0
Time: 88ms
          Asset     Size  Chunks             Chunk Names
    vizceral.js  31.7 kB       0  [emitted]  main
vizceral.js.map  36.2 kB       0  [emitted]  main
    + 1 hidden modules
Hash: e6304a35cf944a95ce14
Version: webpack 1.15.0
Time: 100ms
          Asset     Size  Chunks             Chunk Names
vizceral.min.js  31.7 kB       0  [emitted]  main
    + 1 hidden modules

ERROR in vizceral.min.js from UglifyJs
SyntaxError: Unexpected token: name (_) [./src/vizceral.js:18,0]

**Comment by pnuckowski** [comment]
@prabhurangan Any updates with this?

**Comment by jrsquared** [comment]
You cannot run `npm build:js` from in the `node_modules` directory. It's a different chunk of code than the uncompiled sources directly from github.com/Netflix/vizceral.  If you are trying to work on `vizceral` in the context of `vizceral-example`, you should always just check out both and use `npm link`.

**Comment by prabhurangan** [comment]
Hi

I just followed steps given In the wiki it worked.
Checked out both the project and build worked.

Regards,
Prabhu

**Comment by Rishi5154** [comment]
Hi! Apologies for disturbing y'all on this old issue, but I can't seem to build this whole vizceral-example application.
I ran
`npm link` at /node_modules/vizceral
`npm link` at /vizceral-example
`npm run-script build` at /vizceral-example

> You cannot run `npm build:js` from in the `node_modules` directory. It's a different chunk of code than the uncompiled sources directly from github.com/Netflix/vizceral. If you are trying to work on `vizceral` in the context of `vizceral-example`, you should always just check out both and use `npm link`.


Unfortunately, I still keep running into this issue

```
'npm' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vizceral-example@4.3.0 build: `npm run-script build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vizceral-example@4.3.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Debug log message refers to mostly EventEmitter [errors](https://ibb.co/Zf7T78m).

Would like to clarify what 'checkout' means in this context. Perhaps that could be the missing link. Thanks for the support.
