### ISSUE TITLE
Regional View

### ISSUE THREAD

**Issue by lhayhurst** [Netflix/vizceral-example#4]
Hi, thank you for open sourcing this! Really awesome (and sexy looking!) utility.

Dumb question -- does the example come with [the regional view](http://techblog.netflix.com/2016/08/vizceral-open-source.html)? I've poked around the source and also installed locally (install instructions worked perfectly, thank you!) and it looks like the node drill down from the Global view isn't either enabled or coded up. 

Thank you!

**Comment by jrsquared** [comment]
@lhayhurst Thank you for the kind words.

Yes, it does come with the regional view. When you try to click on one of the nodes in the global view, what happens? Are there any error messages in the console? What browser/version are you using?

**Comment by lhayhurst** [comment]
Thanks for fast response! Yeah, I checked console and an exception is getting thrown

vizceral.js:69975 Uncaught TypeError: Cannot read property 'map' of undefined

**Comment by jrsquared** [comment]
Did you just clone and install today? It sounds like you may be running into the bug I fixed in commit https://github.com/Netflix/vizceral/commit/75b91f36f528d657bbe98c63d00596877a5fc7d3

**Comment by lhayhurst** [comment]
Well caught! That was the issue. I updated and all is well. Thank you!!
