### ISSUE TITLE
Charts not displaying in Internet Explorer v11

### ISSUE THREAD

**Issue by BhanuPatnana** [Netflix/vizceral-example#44]
Canvas is failed to display in IE browser. It is working fine in Chrome and Firefox. 
IE browser showing error at **this.boundingRect = this.renderer.domElement.getBoundingClientRect();**

```
{	    key: 'updateBoundingRectCache',
	    value: function updateBoundingRectCache() {
	      this.boundingRect = this.renderer.domElement.getBoundingClientRect();
	    }
```

I want to know whether Vizceral supports in Internet Explorer browser, if it supports what is the solution to above error

Thanks in advance

**Comment by jrsquared** [comment]
IE is not supported.

https://github.com/Netflix/vizceral#supported-browsers
