### ISSUE TITLE
Example doesn't work with v3.0.3 vizceral 

### ISSUE THREAD

**Issue by fartbagxp** [Netflix/vizceral-example#9]
![image](https://cloud.githubusercontent.com/assets/8839850/18604265/78efb9e0-7c48-11e6-9ff3-14bb1ac4bfea.png)

I was playing around with the latest vizceral, and nothing seems to work anymore.

**Comment by jrsquared** [comment]
You are correct, vizceral-example has not been updated to work with the latest major release of vizceral. I will update vizceral-example as soon as I get a chance.

**Comment by fartbagxp** [comment]
Ah, it's fine, I noticed how hard you were working on the vizceral main project but and since releases were pushed out pretty frequently, I couldn't really tell what all the major changes were.

Is there a CHANGELOG.md somewhere in the main project that can quickly tell me what changed between version 2 and 3?

**Comment by jrsquared** [comment]
About that... A CHANGELOG is on my todo list. :)

The biggest change that called for a major bump was the ability for connections to be highlighted and selected.  This replaced the `nodeHighlighted` event with `objectHighlighted`, and a few other generalizations around node-specific selection.

**Comment by fartbagxp** [comment]
Gotcha. Thanks :)

**Comment by jrsquared** [comment]
Addressed in ef2ed96bdffc6c3bef5b6c6d6729de6aa68f7ae2
